[package]
name = "lipsum-rs"
version = "0.1.0"
authors = ["Matthew Klein <mklein994@gmail.com>"]
edition = "2018"

[[bin]]
name = "lipsum"
path = "src/main.rs"

[dependencies]
clap = { version = "2.32.0", features = ["wrap_help"] }
lipsum = "0.5.0"
rand = "0.6.1"
